name: CI CD static deployment-app

on:
    push:
      branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy Via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script:  |
            cd stop-watch-app
            git pull origin main
            cd
            sudo cp -r stop-watch-app/* /var/www/html
            
            




      
